[2024-10-26T21:53:46.395+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-26T21:53:46.410+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coinmarket_extraction.fetch_coin_data manual__2024-10-26T21:53:43.278713+00:00 [queued]>
[2024-10-26T21:53:46.418+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coinmarket_extraction.fetch_coin_data manual__2024-10-26T21:53:43.278713+00:00 [queued]>
[2024-10-26T21:53:46.420+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-26T21:53:46.433+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): fetch_coin_data> on 2024-10-26 21:53:43.278713+00:00
[2024-10-26T21:53:46.440+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1751) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-26T21:53:46.442+0000] {standard_task_runner.py:72} INFO - Started process 1753 to run task
[2024-10-26T21:53:46.442+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'coinmarket_extraction', 'fetch_coin_data', 'manual__2024-10-26T21:53:43.278713+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/extractor.py', '--cfg-path', '/tmp/tmpjzljjn2o']
[2024-10-26T21:53:46.443+0000] {standard_task_runner.py:105} INFO - Job 147: Subtask fetch_coin_data
[2024-10-26T21:53:46.489+0000] {task_command.py:467} INFO - Running <TaskInstance: coinmarket_extraction.fetch_coin_data manual__2024-10-26T21:53:43.278713+00:00 [running]> on host c94222e110db
[2024-10-26T21:53:46.575+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='coinmarket_extraction' AIRFLOW_CTX_TASK_ID='fetch_coin_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T21:53:43.278713+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T21:53:43.278713+00:00'
[2024-10-26T21:53:46.578+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-26T21:53:46.579+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-26T21:53:46.580+0000] {logging_mixin.py:190} INFO - Current task name:fetch_coin_data state:running start_date:2024-10-26 21:53:46.411078+00:00
[2024-10-26T21:53:46.580+0000] {logging_mixin.py:190} INFO - Dag name:coinmarket_extraction and current dag run status:running
[2024-10-26T21:53:46.581+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-26T21:53:46.929+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extractor.py", line 27, in fetch_coin_data
    with open(original_json_path, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sharif.neto\\Documents\\Dados\\whiteboard_aak\\data/original.json'
[2024-10-26T21:53:46.947+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-26T21:53:46.948+0000] {logging_mixin.py:190} INFO - Task start:2024-10-26 21:53:46.411078+00:00 end:2024-10-26 21:53:46.947390+00:00 duration:0.536312
[2024-10-26T21:53:46.949+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_coin_data> dag:<DAG: coinmarket_extraction> dagrun:<DagRun coinmarket_extraction @ 2024-10-26 21:53:43.278713+00:00: manual__2024-10-26T21:53:43.278713+00:00, state:running, queued_at: 2024-10-26 21:53:43.308861+00:00. externally triggered: True>
[2024-10-26T21:53:46.949+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: 'C:\\Users\\sharif.neto\\Documents\\Dados\\whiteboard_aak\\data/original.json'
[2024-10-26T21:53:46.950+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=coinmarket_extraction, task_id=fetch_coin_data, run_id=manual__2024-10-26T21:53:43.278713+00:00, execution_date=20241026T215343, start_date=20241026T215346, end_date=20241026T215346
[2024-10-26T21:53:46.966+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-26T21:53:46.967+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 147 for task fetch_coin_data ([Errno 2] No such file or directory: 'C:\\Users\\sharif.neto\\Documents\\Dados\\whiteboard_aak\\data/original.json'; 1753)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extractor.py", line 27, in fetch_coin_data
    with open(original_json_path, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sharif.neto\\Documents\\Dados\\whiteboard_aak\\data/original.json'
[2024-10-26T21:53:47.030+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-26T21:53:47.060+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26T21:53:47.065+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
